import Sidebar from "@/components/sidebar";
import { Container, Grid } from "@mui/material";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RTK_Providers from "./providers/rtk-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container sx={{ padding: "1rem" }} maxWidth="xl">
          <Grid container spacing={2}>
            <Grid p={`16px`} item xs={12} md={2}>
              <Sidebar />
            </Grid>
            <Grid p={`16px`} item xs={12} md={10}>
              <RTK_Providers>{children}</RTK_Providers>
            </Grid>
          </Grid>
        </Container>
      </body>
    </html>
  );
}
